name: Check and update Areas

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check_new:
    runs-on: ubuntu-20.04
    steps:
      
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: Install packages
        run: pip install pandas requests
      
      - name: Update Areas
        id: update_areas
        run: |
          output=$(python ./scripts/update.py.py)
          echo "::set-output name=result::$output"
          echo $(date '+%Y-%m-%d %H:%M:%S') - $output
        
      - name: Update Repository
        if: ${{steps.update_areas.outputs.result == 'Done!'}}
        run: |-
          git config user.name "autoupdate"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date --iso-8601=seconds)
          git commit -m "update: ${timestamp}" || exit 0
          git push