name: Check and update Areas

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check_new:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: |-
          pip install -r requirements.txt
          sudo apt-get install sqlite3 sqlite3-tools

      - name: Update Areas
        id: update_areas
        run: |-
          OPENSSL_CONF=config/openssl.cnf python3 ./update.py

      - name: Calculate Diffs
        id: calculate_diffs
        run: |-
          python3 ./diff.py

      - name: Update Repository
        run: |-
          git config user.name "autoupdate"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date --iso-8601=seconds)
          git commit -m "update: ${timestamp}" || exit 0
          git push
